import { useEffect, useMemo, useState } from 'react';
import { useBeforeUnload, useBlocker } from 'react-router-dom';
import type { AdminSettingsData } from '../../admin-types';
import { adminRequest } from '../../api';
import { Badge, Button, Dialog, DialogClose, ErrorState, formatDate, inputClass, LoadingState, PageIntro, Panel } from '../../components/AdminUI';
import { useAdminData } from '../../hooks/useAdminData';

const settingFields = [
  ['announce_channel_id', 'Announcements channel', 'Weekly opt-in and pairing announcements'], ['organizer_channel_id', 'Organizer channel', 'Digests, case files, and operational alerts'],
  ['threads_channel_id', 'Interview threads channel', 'Parent channel for session threads'],
  ['participant_role_id', 'Participant role', 'Granted after completed enrollment'], ['organizer_role_id', 'Organizer role', 'Admin access fallback and Discord permissions'],
] as const;
export function AdminSettingsPage() {
  const { data, error, loading, reload, setData } = useAdminData<AdminSettingsData>('/settings'); const [draft, setDraft] = useState<Record<string, string> | null>(null); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [cohortOpen, setCohortOpen] = useState(false);
  useEffect(() => { if (data && !draft) setDraft({ ...data.settings }); }, [data, draft]);
  const dirty = useMemo(() => Boolean(data && draft && JSON.stringify(data.settings) !== JSON.stringify(draft)), [data, draft]);
  useBeforeUnload((event) => { if (dirty) event.preventDefault(); }); const blocker = useBlocker(dirty);
  if (loading && !data) return <LoadingState />; if (error || !data || !draft) return <ErrorState message={error ?? 'No settings returned.'} onRetry={() => void reload()} />;
  const update = (key: string, value: string) => { setDraft((current) => ({ ...current!, [key]: value })); setSaved(false); };
  const save = async () => { setSaving(true); try { await adminRequest('/settings', { method: 'POST', body: JSON.stringify({ settings: draft }) }); setData((current) => current ? { ...current, settings: { ...draft } } : current); setSaved(true); } finally { setSaving(false); } };
  const createCohort = async (payload: { name: string; startDate: string; rounds: number }) => { await adminRequest('/cohorts', { method: 'POST', body: JSON.stringify(payload) }); setCohortOpen(false); await reload(); setDraft(null); };
  return <div className="space-y-7"><PageIntro title="Program settings" description="Cohort calendar, Discord bindings, delivery behavior, and access. Changes are staged until you save them." actions={<><span className={`text-xs font-bold ${dirty ? 'text-amber-700' : saved ? 'text-emerald-700' : 'text-slate-400'}`}>{dirty ? 'Unsaved changes' : saved ? 'Saved' : 'Up to date'}</span><Button disabled={!dirty || saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save all changes'}</Button></>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-5"><Panel title="Program timeline" description="Nine program weeks wrapped around three two-week technical rounds."><div className="grid gap-px bg-slate-100 sm:grid-cols-2 lg:grid-cols-3">{data.timeline.map((week) => <div key={week.index} className={`bg-white p-4 dark:bg-card ${data.programWeek?.index === week.index ? 'ring-2 ring-inset ring-western-500' : ''}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black uppercase tracking-wider text-western-700">Week {week.index}</span>{week.technicalRound ? <Badge value={`Round ${week.technicalRound}`} /> : null}</div><div className="mt-2 text-sm font-extrabold text-slate-950 dark:text-foreground">{week.title}</div><div className="mt-1 text-xs text-slate-500">{formatDate(week.startsOn, false)}–{formatDate(week.endsOn, false)}</div></div>)}</div></Panel><Panel title="Discord configuration" description="Use snowflake IDs from Discord developer mode."><div className="grid gap-4 p-5 sm:grid-cols-2">{settingFields.map(([key, label, help]) => <label key={key} className="block text-sm font-bold text-slate-800">{label}<input className={`${inputClass} mt-2 font-mono`} value={draft[key] ?? ''} onChange={(event) => update(key, event.target.value)} /><span className="mt-1.5 block text-xs font-normal leading-5 text-slate-500">{help}</span></label>)}</div></Panel><Panel title="Problem delivery" description="Question sets are released at the start of each two-week technical round."><label className="flex cursor-pointer items-start gap-3 p-5"><input className="mt-1" type="checkbox" checked={draft.packet_mode === 'on'} onChange={(event) => update('packet_mode', event.target.checked ? 'on' : 'off')} /><span><span className="block text-sm font-extrabold text-slate-900">Private interviewer packets</span><span className="mt-1 block text-sm leading-6 text-slate-500">When enabled, interviewers receive their signed problem packet as soon as a session time is confirmed. Each Round 1, 2, or 3 set remains active for the full two-week round.</span></span></label></Panel></div>
      <div className="space-y-5"><Panel title="Active matching pool"><div className="p-5"><div className="text-4xl font-black tabular-nums text-slate-950">{data.activeParticipants}</div><div className="mt-1 text-sm text-slate-500">active participants</div><div className={`mt-4 rounded-xl p-3 text-xs font-semibold ${data.activeParticipants >= data.minimumMatchingPool ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{data.activeParticipants >= data.minimumMatchingPool ? 'Ready to match.' : `At least ${data.minimumMatchingPool} active participants are needed. Two cannot satisfy the distinct-partner rule.`}</div></div></Panel><Panel title="Cohorts" actions={<button className="text-xs font-bold text-western-700" onClick={() => setCohortOpen(true)}>New cohort</button>}><div className="divide-y divide-slate-100">{data.cohorts.map((cohort) => <div key={cohort.id} className="p-4"><div className="flex items-center justify-between gap-2"><span className="text-sm font-bold text-slate-900">{cohort.name}</span><Badge value={cohort.status} /></div><div className="mt-1 text-xs text-slate-500">Technical Round 1 starts {formatDate(cohort.start_date, false)} · {cohort.weeks_count} rounds</div></div>)}</div></Panel></div></div>
    {blocker.state === 'blocked' ? <Dialog title="Leave with unsaved changes?" description="Your program setting edits have not been saved." onClose={() => blocker.reset?.()} actions={<><DialogClose><Button variant="secondary">Stay here</Button></DialogClose><Button variant="danger" onClick={() => blocker.proceed?.()}>Discard and leave</Button></>}><p className="text-sm text-slate-600">Save your changes first if you want to keep them.</p></Dialog> : null}
    {cohortOpen ? <CohortDialog onClose={() => setCohortOpen(false)} onCreate={createCohort} activeCount={data.activeParticipants} minimum={data.minimumMatchingPool} /> : null}
  </div>;
}
function CohortDialog({ onClose, onCreate, activeCount, minimum }: { onClose: () => void; onCreate: (payload: { name: string; startDate: string; rounds: number }) => Promise<void>; activeCount: number; minimum: number }) { const [name, setName] = useState(''); const [startDate, setStartDate] = useState(''); const [rounds, setRounds] = useState(3); const [busy, setBusy] = useState(false); const submit = async () => { setBusy(true); try { await onCreate({ name, startDate, rounds }); } finally { setBusy(false); } }; return <Dialog title="Create a new cohort" description="Week 0 begins two weeks before Technical Round 1. This closes any currently active cohort." onClose={onClose} actions={<><DialogClose><Button variant="secondary">Cancel</Button></DialogClose><Button disabled={busy || !name.trim() || !startDate} onClick={() => void submit()}>{busy ? 'Creating…' : 'Create cohort'}</Button></>}><div className="space-y-4"><label className="block text-sm font-bold text-slate-800">Cohort name<input autoFocus className={`${inputClass} mt-2`} placeholder="Western Tech Alumni 2026" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block text-sm font-bold text-slate-800">Technical Round 1 start date<input type="date" className={`${inputClass} mt-2`} value={startDate} onChange={(event) => setStartDate(event.target.value)} /><span className="mt-1.5 block text-xs font-normal text-slate-500">The program timeline starts at Week 0, fourteen days earlier.</span></label><label className="block text-sm font-bold text-slate-800">Number of technical rounds<input type="number" min={1} max={8} className={`${inputClass} mt-2`} value={rounds} onChange={(event) => setRounds(Number(event.target.value))} /></label>{activeCount < minimum ? <div className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">You can create the calendar now, but matching cannot produce valid cohorts until at least {minimum} participants are active. There is no minimum to create or open a cohort.</div> : null}</div></Dialog>; }
