import type { AnalyticsData, CountRow } from '../../admin-types';
import { Badge, ErrorState, LoadingState, Metric, PageIntro, Panel, tableClass, tableWrapClass, tdClass, thClass } from '../../components/AdminUI';
import { useAdminData } from '../../hooks/useAdminData';

export function AnalyticsPage() {
  const { data, error, loading, reload } = useAdminData<AnalyticsData>('/analytics');
  if (loading && !data) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? 'No analytics returned.'} onRetry={() => void reload()} />;
  const totalParticipants = sum(data.participants); const totalSessions = sum(data.sessions); const completed = valueFor(data.sessions, 'completed'); const reportTotal = data.reports.reduce((n, r) => n + Number(r.total), 0); const submitted = data.reports.reduce((n, r) => n + Number(r.submitted), 0);
  return <div className="space-y-7"><PageIntro title="Analytics" description="Cohort outcomes and process quality, kept close to the underlying counts so the numbers stay interpretable." />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Participants" value={totalParticipants} note={`${valueFor(data.participants, 'active')} active`} /><Metric label="Sessions completed" value={totalSessions ? `${Math.round(completed / totalSessions * 100)}%` : '—'} note={`${completed} of ${totalSessions}`} /><Metric label="Report completion" value={reportTotal ? `${Math.round(submitted / reportTotal * 100)}%` : '—'} note={`${submitted} of ${reportTotal}`} /><Metric label="Pass verdicts" value={valueFor(data.verdicts, 'pass')} note={`${valueFor(data.verdicts, 'borderline')} borderline · ${valueFor(data.verdicts, 'fail')} fail`} /></div>
    <div className="grid gap-5 xl:grid-cols-2"><Distribution title="Participant standing" rows={data.participants} /><Distribution title="Session outcomes" rows={data.sessions} /></div>
    <Panel title="Round conversion" description="Opt-ins become directed sessions; completion can lag while a round is live."><div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>Cohort</th><th className={thClass}>Round</th><th className={thClass}>Opt-ins</th><th className={thClass}>Sessions</th><th className={thClass}>Completed</th><th className={thClass}>Completion</th></tr></thead><tbody>{data.rounds.map((row) => <tr key={`${row.cohort}-${row.round}`}><td className={`${tdClass} font-semibold text-slate-900`}>{row.cohort}</td><td className={tdClass}>R{row.round}</td><td className={`${tdClass} tabular-nums`}>{row.optins}</td><td className={`${tdClass} tabular-nums`}>{row.sessions}</td><td className={`${tdClass} tabular-nums`}>{row.completed}</td><td className={tdClass}>{row.sessions ? `${Math.round(row.completed / row.sessions * 100)}%` : '—'}</td></tr>)}</tbody></table></div></Panel>
    <div className="grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><Distribution title="Interviewer verdicts" rows={data.verdicts} /><Panel title="Problem performance" description="Experience rating is directional—not a difficulty score on its own."><div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>Problem</th><th className={thClass}>Difficulty</th><th className={thClass}>Uses</th><th className={thClass}>Avg. experience</th></tr></thead><tbody>{data.problems.map((row) => <tr key={row.id}><td className={`${tdClass} font-semibold text-slate-900`}>{row.title}</td><td className={tdClass}><Badge value={row.difficulty} /></td><td className={`${tdClass} tabular-nums`}>{row.uses}</td><td className={`${tdClass} tabular-nums`}>{row.avg_experience == null ? '—' : Number(row.avg_experience).toFixed(1)}</td></tr>)}</tbody></table></div></Panel></div>
  </div>;
}
function rowLabel(row: CountRow) { return row.label ?? row.status ?? row.state ?? 'unknown'; } function rowValue(row: CountRow) { return Number(row.value ?? row.n ?? 0); } function sum(rows: CountRow[]) { return rows.reduce((n, row) => n + rowValue(row), 0); } function valueFor(rows: CountRow[], label: string) { return rowValue(rows.find((row) => rowLabel(row) === label) ?? {}); }
function Distribution({ title, rows }: { title: string; rows: CountRow[] }) { const total = sum(rows); return <Panel title={title}><div className="space-y-4 p-5">{rows.map((row) => { const value = rowValue(row); const width = total ? value / total * 100 : 0; return <div key={rowLabel(row)}><div className="mb-1.5 flex items-center justify-between"><Badge value={rowLabel(row)} /><span className="text-xs font-bold tabular-nums text-slate-500">{value} · {Math.round(width)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500 transition-[width] duration-500" style={{ width: `${width}%` }} /></div></div>; })}</div></Panel>; }
