import { useMemo, useState } from 'react';
import type { OperationsData, OutboxRow } from '../../admin-types';
import { adminRequest } from '../../api';
import { Badge, Button, EmptyState, ErrorState, formatDate, LoadingState, PageIntro, Panel, tableClass, tableWrapClass, tdClass, thClass, Tabs } from '../../components/AdminUI';
import { useAdminData } from '../../hooks/useAdminData';

export function OperationsPage() {
  const { data, error, loading, reload } = useAdminData<OperationsData>('/operations'); const [tab, setTab] = useState('outbox'); const [retrying, setRetrying] = useState<number | null>(null);
  const failed = useMemo(() => data?.outbox.filter((row) => !row.done_at && row.attempts >= 5).length ?? 0, [data]);
  if (loading && !data) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? 'No operations data returned.'} onRetry={() => void reload()} />;
  const retry = async (row: OutboxRow) => { setRetrying(row.id); try { await adminRequest(`/operations/outbox/${row.id}/retry`, { method: 'POST', body: '{}' }); await reload(); } finally { setRetrying(null); } };
  return <div className="space-y-7"><PageIntro title="Operations" description="Delivery, scheduled work, and organizer actions—the evidence you need when something feels off." />
    {failed ? <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3"><div className="text-sm font-extrabold text-rose-900">{failed} delivery {failed === 1 ? 'item has' : 'items have'} exhausted retries</div><p className="mt-0.5 text-xs text-rose-700">Inspect the error before retrying; a permanent configuration problem will fail again.</p></div> : null}
    <div className="flex"><Tabs value={tab} onChange={setTab} items={[{ value: 'outbox', label: 'Outbox', count: data.outbox.filter((row) => !row.done_at).length }, { value: 'notifications', label: 'Notifications', count: data.notifications.length }, { value: 'jobs', label: 'Cron jobs', count: data.jobs.length }, { value: 'audit', label: 'Audit log', count: data.audit.length }]} /></div>
    {tab === 'outbox' ? <OutboxPanel rows={data.outbox} retrying={retrying} onRetry={retry} /> : tab === 'notifications' ? <NotificationsPanel rows={data.notifications} /> : tab === 'jobs' ? <JobsPanel rows={data.jobs} /> : <AuditPanel rows={data.audit} />}
  </div>;
}
function OutboxPanel({ rows, retrying, onRetry }: { rows: OutboxRow[]; retrying: number | null; onRetry: (row: OutboxRow) => Promise<void> }) { return <Panel title="Durable outbox" description="Pending sends are drained after writes and by cron; exhausted rows stay here.">{rows.length ? <div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>ID</th><th className={thClass}>Kind</th><th className={thClass}>State</th><th className={thClass}>Attempts</th><th className={thClass}>Run after</th><th className={thClass}>Last error</th><th className={thClass}></th></tr></thead><tbody>{rows.map((row) => { const state = row.done_at ? 'sent' : row.attempts >= 5 ? 'failed' : row.attempts ? 'retrying' : 'pending'; return <tr key={row.id}><td className={`${tdClass} font-mono text-xs`}>#{row.id}</td><td className={tdClass}>{row.kind.replaceAll('_', ' ')}</td><td className={tdClass}><Badge value={state} /></td><td className={`${tdClass} tabular-nums`}>{row.attempts}/5</td><td className={tdClass}>{formatDate(row.run_after)}</td><td className={`${tdClass} max-w-xs truncate text-xs text-rose-700`} title={row.last_error ?? ''}>{row.last_error ?? '—'}</td><td className={`${tdClass} text-right`}>{state === 'failed' ? <Button variant="secondary" disabled={retrying === row.id} onClick={() => void onRetry(row)}>{retrying === row.id ? 'Retrying…' : 'Retry'}</Button> : null}</td></tr>; })}</tbody></table></div> : <EmptyState title="Outbox is empty" description="Queued messages and emails will appear here." />}</Panel>; }
function NotificationsPanel({ rows }: { rows: Array<Record<string, any>> }) { return <Panel title="Notification history"><div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>When</th><th className={thClass}>Participant</th><th className={thClass}>Channel</th><th className={thClass}>Kind</th><th className={thClass}>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className={tdClass}>{formatDate(row.created_at)}</td><td className={tdClass}>{row.name ?? '—'}</td><td className={tdClass}>{row.channel}</td><td className={tdClass}>{row.kind?.replaceAll('_', ' ')}</td><td className={tdClass}><Badge value={row.status} /></td></tr>)}</tbody></table></div></Panel>; }
function JobsPanel({ rows }: { rows: Array<Record<string, any>> }) { return <Panel title="Cron idempotency ledger" description="A row means that scheduled transition has already run."><div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>Ran</th><th className={thClass}>Job key</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className={tdClass}>{formatDate(row.ran_at)}</td><td className={`${tdClass} font-mono text-xs text-slate-800`}>{row.job_key}</td></tr>)}</tbody></table></div></Panel>; }
function AuditPanel({ rows }: { rows: OperationsData['audit'] }) { return <Panel title="Organizer audit log" description="Consequential web actions are append-only."><div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>When</th><th className={thClass}>Actor</th><th className={thClass}>Action</th><th className={thClass}>Target</th><th className={thClass}>Detail</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className={tdClass}>{formatDate(row.created_at)}</td><td className={tdClass}>{row.actor_name ?? 'System'}</td><td className={`${tdClass} font-semibold text-slate-900`}>{row.action.replaceAll('.', ' · ').replaceAll('_', ' ')}</td><td className={tdClass}>{row.target_type ? `${row.target_type} ${row.target_id ?? ''}` : '—'}</td><td className={`${tdClass} max-w-xs truncate font-mono text-xs`} title={row.detail ?? ''}>{row.detail ?? '—'}</td></tr>)}</tbody></table></div></Panel>; }
