import { useDeferredValue, useMemo, useState } from 'react';
import type { ParticipantDetail, ParticipantRow, ParticipantsData } from '../../admin-types';
import { adminRequest } from '../../api';
import { Badge, Button, Dialog, EmptyState, ErrorState, formatDate, inputClass, LoadingState, PageIntro, Panel, tableClass, tableWrapClass, tdClass, thClass } from '../../components/AdminUI';
import { useAdminData } from '../../hooks/useAdminData';

export function ParticipantsPage() {
  const { data, error, loading, reload } = useAdminData<ParticipantsData>('/participants');
  const [query, setQuery] = useState(''); const deferredQuery = useDeferredValue(query);
  const [status, setStatus] = useState('all'); const [selected, setSelected] = useState<Set<number>>(() => new Set());
  const [detail, setDetail] = useState<ParticipantDetail | null>(null); const [detailLoading, setDetailLoading] = useState(false);
  const [bulkOpen, setBulkOpen] = useState<'status' | 'message' | null>(null); const [busy, setBusy] = useState(false); const [syncing, setSyncing] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const filtered = useMemo(() => {
    const needle = deferredQuery.trim().toLowerCase();
    return (data?.participants ?? []).filter((participant) => (status === 'all' || participant.status === status) && (!needle || [participant.name, participant.discord_nickname, participant.discord_username, participant.discord_id, participant.preferred_email, participant.western_email, participant.program, participant.year].some((value) => value?.toLowerCase().includes(needle))));
  }, [data, deferredQuery, status]);
  if (loading && !data) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? 'No roster returned.'} onRetry={() => void reload()} />;

  const allVisibleSelected = filtered.length > 0 && filtered.every((row) => selected.has(row.id));
  const toggleAll = () => setSelected((current) => { const next = new Set(current); if (allVisibleSelected) filtered.forEach((row) => next.delete(row.id)); else filtered.forEach((row) => next.add(row.id)); return next; });
  const openDetail = async (participant: ParticipantRow) => { setDetailLoading(true); setDetail(null); try { setDetail(await adminRequest<ParticipantDetail>(`/participants/${participant.id}`)); } finally { setDetailLoading(false); } };
  const runStatus = async (value: string, note: string) => { setBusy(true); try { const result = await adminRequest<{ updated: number }>('/participants/status', { method: 'POST', body: JSON.stringify({ ids: [...selected], status: value, note }) }); setNotice(`${result.updated} participant${result.updated === 1 ? '' : 's'} updated.`); setSelected(new Set()); setBulkOpen(null); await reload(); } finally { setBusy(false); } };
  const runMessage = async (channel: string, message: string) => { setBusy(true); try { const result = await adminRequest<{ queued: number; skipped: number }>('/participants/message', { method: 'POST', body: JSON.stringify({ ids: [...selected], channel, message }) }); setNotice(`${result.queued} message${result.queued === 1 ? '' : 's'} queued${result.skipped ? `; ${result.skipped} skipped` : ''}.`); setSelected(new Set()); setBulkOpen(null); } finally { setBusy(false); } };
  const syncDiscord = async () => { setSyncing(true); try { const result = await adminRequest<{ queued: number }>('/participants/sync-discord', { method: 'POST', body: '{}' }); setNotice(`${result.queued} Discord identit${result.queued === 1 ? 'y' : 'ies'} queued for refresh. Updated names will appear as the outbox drains.`); } finally { setSyncing(false); } };

  return <div className="space-y-7">
    <PageIntro title="Participants" description="Search the roster, inspect a participant’s full history, and take deliberate bulk actions." actions={<><Button variant="secondary" disabled={syncing} onClick={() => void syncDiscord()}>{syncing ? 'Queueing sync…' : 'Sync Discord identities'}</Button><a href="/api/admin/participants.csv" className="rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Export CSV</a></>} />
    {notice ? <div className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="Dismiss">×</button></div> : null}
    <Panel>
      <div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row lg:items-center">
        <input className={`${inputClass} lg:max-w-sm`} type="search" placeholder="Search name, email, program…" value={query} onChange={(event) => setQuery(event.target.value)} />
        <select className={`${inputClass} lg:w-44`} value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{['active', 'paused', 'held', 'removed', 'completed'].map((value) => <option key={value}>{value}</option>)}</select>
        <div className="text-xs font-semibold text-slate-500 lg:ml-auto">{filtered.length} of {data.participants.length}</div>
      </div>
      {selected.size ? <div className="flex flex-wrap items-center gap-2 border-b border-slate-200 bg-slate-950 px-4 py-2.5 text-white"><span className="mr-2 text-xs font-bold tabular-nums">{selected.size} selected</span><Button variant="secondary" className="!border-white/10 !bg-white/10 !py-1.5 !text-white hover:!bg-white/15" onClick={() => setBulkOpen('status')}>Change status</Button><Button variant="secondary" className="!border-white/10 !bg-white/10 !py-1.5 !text-white hover:!bg-white/15" onClick={() => setBulkOpen('message')}>Send message</Button><button className="ml-auto text-xs font-bold text-slate-300 hover:text-white" onClick={() => setSelected(new Set())}>Clear</button></div> : null}
      {filtered.length ? <div className={tableWrapClass}><table className={tableClass}>
        <thead><tr><th className={`${thClass} w-10`}><input type="checkbox" aria-label="Select visible participants" checked={allVisibleSelected} onChange={toggleAll} /></th><th className={thClass}>Participant</th><th className={thClass}>Program</th><th className={thClass}>Progress</th><th className={thClass}>Signals</th><th className={thClass}>Status</th></tr></thead>
        <tbody>{filtered.map((participant) => <tr key={participant.id} className="group hover:bg-slate-50/70">
          <td className={tdClass}><input type="checkbox" aria-label={`Select ${participant.name}`} checked={selected.has(participant.id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(participant.id)) next.delete(participant.id); else next.add(participant.id); return next; })} /></td>
          <td className={tdClass}><button className="cursor-pointer text-left" onClick={() => void openDetail(participant)}><span className="block font-bold text-slate-950 group-hover:text-emerald-700">{participant.name ?? '(unnamed)'}</span><span className="mt-1 block text-xs font-semibold text-slate-600">Server nickname: {participant.discord_nickname ?? 'not synced'}</span><span className="block text-xs font-semibold text-indigo-600">Discord: {participant.discord_username ? `@${participant.discord_username}` : 'not synced'}</span><span className="block font-mono text-[0.65rem] text-slate-400">ID {participant.discord_id}</span><span className="block text-xs text-slate-500">{participant.preferred_email}</span></button></td>
          <td className={tdClass}><span className="block text-slate-800">{participant.year ?? '—'}</span><span className="text-xs">{participant.program ?? '—'}</span></td>
          <td className={tdClass}><span className="font-bold tabular-nums text-slate-800">{participant.interviewer_credits}/3 · {participant.interviewee_credits}/3</span><span className="mt-1 block text-[0.68rem] text-slate-400">interviewer · interviewee</span></td>
          <td className={tdClass}><div className="flex flex-wrap gap-1.5">{participant.strikes ? <span className="rounded-full bg-rose-50 px-2 py-0.5 text-xs font-bold text-rose-700">{participant.strikes} strike{participant.strikes === 1 ? '' : 's'}</span> : null}{participant.reports_owed ? <span className="rounded-full bg-amber-50 px-2 py-0.5 text-xs font-bold text-amber-700">{participant.reports_owed} owed</span> : null}{participant.opted_in ? <span className="rounded-full bg-sky-50 px-2 py-0.5 text-xs font-bold text-sky-700">opted in</span> : null}{participant.email_ok ? <span title="Email reminders enabled" className="text-xs text-slate-400">email ✓</span> : null}</div></td>
          <td className={tdClass}><Badge value={participant.status} /></td>
        </tr>)}</tbody>
      </table></div> : <EmptyState title="No participants match" description="Try a broader search or a different status filter." />}
    </Panel>
    {(detail || detailLoading) ? <ParticipantDrawer detail={detail} loading={detailLoading} onClose={() => { setDetail(null); setDetailLoading(false); }} /> : null}
    {bulkOpen === 'status' ? <StatusDialog count={selected.size} busy={busy} onClose={() => setBulkOpen(null)} onSubmit={runStatus} /> : null}
    {bulkOpen === 'message' ? <MessageDialog count={selected.size} busy={busy} onClose={() => setBulkOpen(null)} onSubmit={runMessage} /> : null}
  </div>;
}

function ParticipantDrawer({ detail, loading, onClose }: { detail: ParticipantDetail | null; loading: boolean; onClose: () => void }) {
  return <Dialog wide title={detail?.participant.name ?? 'Participant'} description={detail ? `Server nickname: ${detail.participant.discord_nickname ?? 'not synced'} · Discord: ${detail.participant.discord_username ? `@${detail.participant.discord_username}` : 'not synced'} · ID ${detail.participant.discord_id}` : 'Loading participant history…'} onClose={onClose}>
    {loading || !detail ? <LoadingState /> : <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-4"><Fact label="Status"><Badge value={detail.participant.status} /></Fact><Fact label="Program" value={`${detail.participant.year ?? '—'} · ${detail.participant.program ?? '—'}`} /><Fact label="Experience" value={detail.participant.experience_band ?? '—'} /><Fact label="Joined" value={formatDate(detail.participant.created_at, false)} /></div><div><h3 className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">Sessions</h3><div className="rounded-xl border border-slate-200">{detail.sessions.length ? detail.sessions.map((session) => <div key={session.id} className="flex flex-wrap items-center gap-x-4 gap-y-1 border-b border-slate-100 px-4 py-3 last:border-0"><span className="font-bold text-slate-900">R{session.round} · #{session.id}</span><span className="text-sm text-slate-600">{session.interviewer_name} → {session.interviewee_name}</span><Badge value={session.state} /><span className="ml-auto text-xs text-slate-500">{session.reports_in}/2 reports</span></div>) : <div className="p-4 text-sm text-slate-500">No sessions yet.</div>}</div></div><div className="grid gap-5 lg:grid-cols-2"><div><h3 className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">Incidents</h3>{detail.incidents.length ? detail.incidents.map((incident) => <div key={incident.id} className="mb-2 rounded-xl border border-slate-200 p-3 text-sm"><Badge value={incident.kind} /> <span className="ml-2 text-slate-600">{incident.state} · {formatDate(incident.created_at)}</span></div>) : <p className="text-sm text-slate-500">No incidents.</p>}</div><div><h3 className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">Audit history</h3>{detail.audit.length ? detail.audit.map((row) => <div key={row.id} className="mb-2 text-sm"><span className="font-semibold text-slate-800">{row.action.replaceAll('.', ' ')}</span><span className="ml-2 text-xs text-slate-500">{formatDate(row.created_at)}</span></div>) : <p className="text-sm text-slate-500">No organizer actions recorded.</p>}</div></div></div>}
  </Dialog>;
}
function Fact({ label, value, children }: { label: string; value?: string; children?: React.ReactNode }) { return <div className="rounded-xl bg-slate-50 p-3"><div className="text-[0.65rem] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-sm font-bold text-slate-800">{children ?? value}</div></div>; }
function StatusDialog({ count, busy, onClose, onSubmit }: { count: number; busy: boolean; onClose: () => void; onSubmit: (status: string, note: string) => Promise<void> }) { const [status, setStatus] = useState('active'); const [note, setNote] = useState(''); return <Dialog title={`Change status for ${count}`} description="Status changes affect matching eligibility immediately and are written to the audit log." onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={busy} onClick={() => void onSubmit(status, note)}>{busy ? 'Saving…' : 'Apply change'}</Button></>}><label className="text-sm font-bold text-slate-800">New status<select className={`${inputClass} mt-2`} value={status} onChange={(event) => setStatus(event.target.value)}>{['active', 'paused', 'held', 'removed', 'completed'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="mt-4 block text-sm font-bold text-slate-800">Internal note <span className="font-normal text-slate-400">(optional)</span><textarea className={`${inputClass} mt-2 min-h-24`} value={note} onChange={(event) => setNote(event.target.value)} /></label></Dialog>; }
function MessageDialog({ count, busy, onClose, onSubmit }: { count: number; busy: boolean; onClose: () => void; onSubmit: (channel: string, message: string) => Promise<void> }) { const [channel, setChannel] = useState('dm'); const [message, setMessage] = useState(''); return <Dialog title={`Message ${count} participant${count === 1 ? '' : 's'}`} description="Messages enter the durable outbox. Email is sent only to participants who opted in." onClose={onClose} actions={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={busy || !message.trim()} onClick={() => void onSubmit(channel, message)}>{busy ? 'Queueing…' : 'Queue messages'}</Button></>}><label className="text-sm font-bold text-slate-800">Channel<select className={`${inputClass} mt-2`} value={channel} onChange={(event) => setChannel(event.target.value)}><option value="dm">Discord DM</option><option value="email">Email (opted-in only)</option></select></label><label className="mt-4 block text-sm font-bold text-slate-800">Message<textarea autoFocus maxLength={1900} className={`${inputClass} mt-2 min-h-36`} value={message} onChange={(event) => setMessage(event.target.value)} /></label><div className="mt-1 text-right text-xs tabular-nums text-slate-400">{message.length}/1900</div></Dialog>; }
