import { useEffect, useMemo, useState } from 'react';
import type { ProblemRow, ProblemsData } from '../../admin-types';
import { adminRequest } from '../../api';
import { Badge, Button, Dialog, DialogClose, EmptyState, ErrorState, inputClass, LoadingState, PageIntro, Panel, tableClass, tableWrapClass, tdClass, thClass, Tabs } from '../../components/AdminUI';
import { Checkbox } from '../../components/ui/checkbox';
import { ScrollArea } from '../../components/ui/scroll-area';
import { useAdminData } from '../../hooks/useAdminData';

const blankProblem: Omit<ProblemRow, 'id' | 'uses' | 'exposures'> = { source: 'manual', number: null, title: '', url: null, difficulty: 'medium', difficulty_rank: 2, statement_md: '', hints_md: '', solution_md: '', active: 1 };
export function ProblemsPage() {
  const { data, error, loading, reload } = useAdminData<ProblemsData>('/problems'); const [tab, setTab] = useState('sets'); const [query, setQuery] = useState(''); const [difficulty, setDifficulty] = useState('all'); const [editor, setEditor] = useState<ProblemRow | typeof blankProblem | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const rows = useMemo(() => (data?.problems ?? []).filter((problem) => (difficulty === 'all' || problem.difficulty === difficulty) && (!query.trim() || `${problem.number ?? ''} ${problem.title}`.toLowerCase().includes(query.trim().toLowerCase()))), [data, difficulty, query]);
  if (loading && !data) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? 'No problem data returned.'} onRetry={() => void reload()} />;
  const save = async (problem: any) => { setBusy(true); try { const existing = 'id' in problem; await adminRequest(existing ? `/problems/${problem.id}` : '/problems', { method: 'POST', body: JSON.stringify({ source: problem.source, number: problem.number, title: problem.title, url: problem.url, difficulty: problem.difficulty, difficultyRank: problem.difficulty_rank, statement: problem.statement_md, hints: problem.hints_md, solution: problem.solution_md, active: Boolean(problem.active) }) }); setEditor(null); setNotice(existing ? 'Problem saved.' : 'Problem added.'); await reload(); } finally { setBusy(false); } };
  return <div className="space-y-7"><PageIntro title="Problem bank" description="Build future round sets in advance and curate the source library behind them." actions={<Button onClick={() => setEditor({ ...blankProblem })}>Add problem</Button>} />{notice ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{notice}</div> : null}
    <div className="flex"><Tabs value={tab} onChange={setTab} items={[{ value: 'sets', label: 'Round sets', count: data.weeks.length }, { value: 'library', label: 'Problem library', count: data.problems.length }]} /></div>
    {tab === 'sets' ? <RoundSets data={data} reload={reload} onNotice={setNotice} /> : <Panel><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><input className={`${inputClass} sm:max-w-sm`} type="search" placeholder="Search title or number…" value={query} onChange={(event) => setQuery(event.target.value)} /><select className={`${inputClass} sm:w-40`} value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option value="all">All difficulties</option><option>easy</option><option>medium</option><option>hard</option></select><div className="self-center text-xs font-semibold text-slate-500 sm:ml-auto">{rows.length} problems</div></div>{rows.length ? <div className={tableWrapClass}><table className={tableClass}><thead><tr><th className={thClass}>Problem</th><th className={thClass}>Difficulty</th><th className={thClass}>Content</th><th className={thClass}>Usage</th><th className={thClass}>State</th><th className={thClass}></th></tr></thead><tbody>{rows.map((problem) => <tr key={problem.id}><td className={tdClass}><div className="font-bold text-slate-950">{problem.number ? `#${problem.number} · ` : ''}{problem.title}</div><div className="mt-0.5 text-xs text-slate-400">{problem.source}</div></td><td className={tdClass}><Badge value={problem.difficulty} />{problem.difficulty_rank != null ? <span className="ml-2 text-xs font-bold tabular-nums text-slate-400">{problem.difficulty_rank}</span> : null}</td><td className={tdClass}><div className="flex gap-1.5">{problem.statement_md ? <span title="Statement" className="rounded bg-slate-100 px-1.5 py-1 text-xs">S</span> : null}{problem.hints_md ? <span title="Hints" className="rounded bg-slate-100 px-1.5 py-1 text-xs">H</span> : null}{problem.solution_md ? <span title="Solution" className="rounded bg-slate-100 px-1.5 py-1 text-xs">✓</span> : null}</div></td><td className={tdClass}><span className="font-bold tabular-nums text-slate-800">{problem.uses}</span><span className="ml-1 text-xs">sessions</span></td><td className={tdClass}><Badge value={problem.active ? 'active' : 'inactive'} /></td><td className={`${tdClass} text-right`}><button className="text-sm font-bold text-western-700 hover:text-western-800" onClick={() => setEditor(problem)}>Edit</button></td></tr>)}</tbody></table></div> : <EmptyState title="No problems match" description="Change your filters or add a problem to the bank." />}</Panel>}
    {editor ? <ProblemEditor value={editor} busy={busy} onClose={() => setEditor(null)} onSave={save} /> : null}
  </div>;
}

function RoundSets({ data, reload, onNotice }: { data: ProblemsData; reload: () => Promise<void>; onNotice: (notice: string) => void }) {
  const [weekId, setWeekId] = useState(data.weeks[0]?.id ?? 0); const [draft, setDraft] = useState<number[]>([]); const [size, setSize] = useState(5); const [busy, setBusy] = useState(false);
  const saved = useMemo(() => data.sets.filter((row) => row.week_id === weekId).map((row) => row.problem_id), [data.sets, weekId]);
  useEffect(() => setDraft(saved), [saved]);
  const selectedWeek = data.weeks.find((week) => week.id === weekId); const activeProblems = data.problems.filter((problem) => problem.active); const savedSet = new Set(saved); const dirty = draft.length !== saved.length || draft.some((id) => !savedSet.has(id));
  if (!data.cohort || !data.weeks.length) return <Panel><EmptyState title="No active cohort" description="Create a cohort calendar before staging round sets." /></Panel>;
  const toggle = (id: number) => setDraft((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const save = async () => { setBusy(true); try { await adminRequest(`/problem-sets/${weekId}`, { method: 'PUT', body: JSON.stringify({ problemIds: draft }) }); await reload(); onNotice(`Round ${selectedWeek?.idx} set saved with ${draft.length} problem${draft.length === 1 ? '' : 's'}.`); } finally { setBusy(false); } };
  const generate = async () => { setBusy(true); try { await adminRequest(`/problem-sets/${weekId}/generate`, { method: 'POST', body: JSON.stringify({ size }) }); await reload(); onNotice(`Round ${selectedWeek?.idx} set auto-filled.`); } finally { setBusy(false); } };
  const band = data.bands[String(Math.min(selectedWeek?.idx ?? 3, 3))];
  return <Panel title={`${data.cohort.name} · Round ${selectedWeek?.idx ?? '—'}`} description={band ? `Recommended difficulty rank ${band[0]}–${band[1]}. Future rounds remain staged until they become current.` : 'Choose the problems available for this round.'} actions={<div className="flex items-center gap-2"><select aria-label="Auto-fill size" className={`${inputClass} w-20 py-2`} value={size} onChange={(event) => setSize(Number(event.target.value))}>{[3, 4, 5, 6, 8, 10].map((value) => <option key={value}>{value}</option>)}</select><Button variant="secondary" disabled={busy} onClick={() => void generate()}>Auto-fill</Button><Button disabled={busy || !dirty} onClick={() => void save()}>{busy ? 'Saving…' : 'Save set'}</Button></div>}>
    <div className="border-b border-slate-100 p-4"><Tabs value={String(weekId)} onChange={(value) => setWeekId(Number(value))} items={data.weeks.map((week) => ({ value: String(week.id), label: `Round ${week.idx}`, count: data.sets.filter((row) => row.week_id === week.id).length }))} /></div>
    <ScrollArea className="h-[min(58vh,38rem)]"><div className="grid gap-2 p-4 sm:grid-cols-2 xl:grid-cols-3">{activeProblems.map((problem) => { const checked = draft.includes(problem.id); return <label key={problem.id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 transition ${checked ? 'border-western-300 bg-western-50 dark:bg-western-950/30' : 'border-slate-200 bg-white hover:bg-slate-50'}`}><Checkbox className="mt-0.5" checked={checked} onCheckedChange={() => toggle(problem.id)} /><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-900">{problem.number ? `#${problem.number} · ` : ''}{problem.title}</span><span className="mt-1 flex items-center gap-2"><Badge value={problem.difficulty} /><span className="text-xs text-slate-500">rank {problem.difficulty_rank ?? 'default'} · {problem.uses} uses</span></span></span></label>; })}</div></ScrollArea>
  </Panel>;
}
function ProblemEditor({ value, busy, onClose, onSave }: { value: ProblemRow | typeof blankProblem; busy: boolean; onClose: () => void; onSave: (value: ProblemRow | typeof blankProblem) => Promise<void> }) { const [draft, setDraft] = useState(value); const update = (key: string, value: unknown) => setDraft((current) => ({ ...current, [key]: value })); return <Dialog wide title={'id' in draft ? `Edit ${draft.title}` : 'Add problem'} description="Markdown is stored as source and rendered in interviewer packets." onClose={onClose} actions={<><DialogClose><Button variant="secondary">Cancel</Button></DialogClose><Button disabled={busy || !draft.title.trim()} onClick={() => void onSave(draft)}>{busy ? 'Saving…' : 'Save problem'}</Button></>}><div className="grid gap-4 sm:grid-cols-[8rem_minmax(0,1fr)]"><Field label="Number"><input type="number" className={inputClass} value={draft.number ?? ''} onChange={(event) => update('number', event.target.value ? Number(event.target.value) : null)} /></Field><Field label="Title"><input autoFocus className={inputClass} value={draft.title} onChange={(event) => update('title', event.target.value)} /></Field><Field label="Difficulty"><select className={inputClass} value={draft.difficulty} onChange={(event) => update('difficulty', event.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></Field><Field label="Difficulty rank"><input type="number" step="0.1" className={inputClass} value={draft.difficulty_rank ?? ''} onChange={(event) => update('difficulty_rank', event.target.value ? Number(event.target.value) : null)} /></Field><div className="sm:col-span-2"><Field label="Source URL"><input className={inputClass} value={draft.url ?? ''} onChange={(event) => update('url', event.target.value)} /></Field></div><div className="sm:col-span-2"><Field label="Statement"><textarea className={`${inputClass} min-h-32 font-mono`} value={draft.statement_md ?? ''} onChange={(event) => update('statement_md', event.target.value)} /></Field></div><div className="sm:col-span-2"><Field label="Hint ladder"><textarea className={`${inputClass} min-h-28`} value={draft.hints_md ?? ''} onChange={(event) => update('hints_md', event.target.value)} /></Field></div><div className="sm:col-span-2"><Field label="Solution"><textarea className={`${inputClass} min-h-36 font-mono`} value={draft.solution_md ?? ''} onChange={(event) => update('solution_md', event.target.value)} /></Field></div><label className="sm:col-span-2 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-800"><input type="checkbox" checked={Boolean(draft.active)} onChange={(event) => update('active', event.target.checked ? 1 : 0)} />Active in the problem bank</label></div></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-slate-800">{label}<div className="mt-2">{children}</div></label>; }
