import { useMemo, useState } from 'react';
import type { ReviewRow, ReviewsData } from '../../admin-types';
import { adminRequest } from '../../api';
import { Badge, Button, Dialog, DialogClose, EmptyState, ErrorState, LoadingState, PageIntro, Panel, Tabs } from '../../components/AdminUI';
import { useAdminData } from '../../hooks/useAdminData';

export function ReviewsPage() {
  const { data, error, loading, reload, setData } = useAdminData<ReviewsData>('/reviews');
  const [tab, setTab] = useState('pending'); const [decision, setDecision] = useState<{ row: ReviewRow; action: 'verify' | 'flag' | 'reset' } | null>(null); const [busy, setBusy] = useState(false);
  const rows = useMemo(() => data?.reviews.filter((row) => tab === 'all' || row.review_state === tab) ?? [], [data, tab]);
  if (loading && !data) return <LoadingState />;
  if (error || !data) return <ErrorState message={error ?? 'No reviews returned.'} onRetry={() => void reload()} />;
  const decide = async (row: ReviewRow, action: 'verify' | 'flag' | 'reset', note: string) => { setBusy(true); try { const result = await adminRequest<{ state: string }>(`/reviews/${row.id}`, { method: 'POST', body: JSON.stringify({ action, note }) }); setData((current) => current ? { reviews: current.reviews.map((item) => item.id === row.id ? { ...item, review_state: result.state } : item) } : current); setDecision(null); } finally { setBusy(false); } };
  return <div className="space-y-7"><PageIntro title="Recording reviews" description="Final-round pass verdicts wait for a human recording check. Verification can unlock alumni-round eligibility." />
    <div className="flex"><Tabs value={tab} onChange={setTab} items={[{ value: 'pending', label: 'Pending', count: data.reviews.filter((r) => r.review_state === 'pending').length }, { value: 'flagged', label: 'Flagged', count: data.reviews.filter((r) => r.review_state === 'flagged').length }, { value: 'verified', label: 'Verified', count: data.reviews.filter((r) => r.review_state === 'verified').length }, { value: 'all', label: 'All', count: data.reviews.length }]} /></div>
    {rows.length ? <div className="grid gap-4 2xl:grid-cols-2">{rows.map((row) => <Panel key={row.id} className="flex flex-col"><div className="flex flex-1 flex-col p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold text-slate-400">Session #{row.id} · Round {row.round}</div><h2 className="mt-1 font-black text-slate-950">{row.interviewer_name} <span className="font-normal text-slate-300">→</span> {row.interviewee_name}</h2></div><Badge value={row.review_state} /></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2"><span className="text-xs font-black uppercase tracking-wider text-slate-400">Interviewer verdict</span><Badge value={row.verdict} /></div><p className="mt-2 text-sm leading-6 text-slate-600">{row.verdict_reason || 'No verdict explanation was submitted.'}</p></div><div className="mt-4">{row.video_url ? <a href={row.video_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-western-700 hover:text-western-800">Open recording ↗</a> : <span className="text-sm font-bold text-rose-700">Recording link missing</span>}</div></div><div className="flex flex-wrap justify-end gap-2 border-t border-slate-100 px-5 py-3">{row.review_state !== 'verified' ? <Button variant="secondary" onClick={() => setDecision({ row, action: 'flag' })}>Flag</Button> : <Button variant="secondary" onClick={() => setDecision({ row, action: 'reset' })}>Return to queue</Button>}{row.review_state !== 'verified' ? <Button onClick={() => setDecision({ row, action: 'verify' })} disabled={!row.video_url}>Verify pass</Button> : null}</div></Panel>)}</div> : <Panel><EmptyState title={`No ${tab} reviews`} description="Review items move here automatically when final-round reports are submitted." /></Panel>}
    {decision ? <DecisionDialog decision={decision} busy={busy} onClose={() => setDecision(null)} onSubmit={decide} /> : null}
  </div>;
}
function DecisionDialog({ decision, busy, onClose, onSubmit }: { decision: { row: ReviewRow; action: 'verify' | 'flag' | 'reset' }; busy: boolean; onClose: () => void; onSubmit: (row: ReviewRow, action: 'verify' | 'flag' | 'reset', note: string) => Promise<void> }) { const [note, setNote] = useState(''); const copy = decision.action === 'verify' ? ['Verify this recording?', 'This may mark the participant eligible when their 6/6 credits are complete.', 'Verify pass'] : decision.action === 'flag' ? ['Flag this review?', 'The item remains visible for organizer follow-up.', 'Flag review'] : ['Return this review to pending?', 'Use this if a verified decision needs another look.', 'Return to queue']; return <Dialog title={copy[0]} description={copy[1]} onClose={onClose} actions={<><DialogClose><Button variant="secondary">Cancel</Button></DialogClose><Button variant={decision.action === 'flag' ? 'danger' : 'primary'} disabled={busy} onClick={() => void onSubmit(decision.row, decision.action, note)}>{busy ? 'Saving…' : copy[2]}</Button></>}><label className="text-sm font-bold text-slate-800">Internal note <span className="font-normal text-slate-400">(optional)</span><textarea className="mt-2 min-h-24 w-full rounded-lg border border-slate-200 p-3 text-sm" value={note} onChange={(event) => setNote(event.target.value)} /></label></Dialog>; }
