import { useEffect, useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { Link } from 'react-router-dom';
import { publicRequest } from '../api';
import { PublicIntro, PublicShell } from '../components/PublicShell';

type BankData = { public: boolean; cohort: { name: string } | null; round: number | null; problems: Array<{ number: number | null; title: string; url: string | null; difficulty: string }> };
export function BankPage() {
  const [data, setData] = useState<BankData | null>(null); const [error, setError] = useState('');
  useEffect(() => { publicRequest<BankData>('/public/bank').then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : 'Could not load the bank.')); }, []);
  const isPrivate = data?.public === false;
  return <PublicShell><PublicIntro eyebrow={isPrivate ? 'Private question delivery' : 'Open problem bank'} title={isPrivate ? 'Questions are shared per interview' : data?.round ? `Round ${data.round} questions` : 'Question bank'} description={isPrivate ? 'WTA assigns a problem to each session and sends it directly to the interviewer after the time is confirmed.' : data?.cohort ? `${data.cohort.name}. Interviewers choose one problem per session; participants can study the published set.` : 'The active round’s published practice set.'} />
    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-900 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200">{error}</div> : !data ? <div className="h-72 animate-pulse rounded-3xl bg-slate-200 dark:bg-muted" /> : isPrivate ? <div className="rounded-3xl border border-border bg-card p-8 text-center shadow-sm sm:p-12"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-western-100 text-western-800 dark:bg-western-950 dark:text-western-300"><LockKeyhole className="size-6" /></span><h2 className="mt-5 text-xl font-black text-foreground">The public question bank is closed</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Interviewers receive a private, signed packet for their assigned session. Separate practice problems remain available from your dashboard.</p><Link to="/login" className="mt-6 inline-flex rounded-xl bg-western-800 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-western-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-western-500 focus-visible:ring-offset-2 motion-reduce:transform-none dark:bg-western-500 dark:text-slate-950 dark:hover:bg-western-400">Open dashboard</Link></div> : !data.problems.length ? <div className="rounded-3xl border border-border bg-card p-12 text-center"><h2 className="font-black text-foreground">Nothing published yet</h2><p className="mt-2 text-sm text-muted-foreground">Check back before the round begins.</p></div> : <div className="grid gap-4 sm:grid-cols-2">{data.problems.map((problem) => <a key={`${problem.number}-${problem.title}`} href={problem.url ?? '#'} target={problem.url ? '_blank' : undefined} rel="noreferrer" className="group rounded-2xl border border-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-western-300 hover:shadow-lg motion-reduce:transform-none"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-[0.15em] text-muted-foreground">{problem.number ? `#${problem.number}` : 'WTA'}</span><span className="rounded-full bg-muted px-2 py-1 text-[0.65rem] font-black uppercase text-muted-foreground">{problem.difficulty}</span></div><h2 className="mt-5 text-lg font-black text-foreground group-hover:text-western-800 dark:group-hover:text-western-300">{problem.title}</h2><div className="mt-3 text-xs font-bold text-western-700 dark:text-western-300">Open problem ↗</div></a>)}</div>}
  </PublicShell>;
}
